# Generated by Django 4.0.5 on 2022-08-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('mailing_name', models.CharField(max_length=225)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('telephone', models.CharField(max_length=225)),
                ('mobile', models.CharField(max_length=225)),
                ('fax', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=225)),
                ('fin_begin', models.DateField(null=True)),
                ('books_begin', models.DateField(null=True)),
                ('state', models.CharField(default=True, max_length=225)),
                ('country', models.CharField(default=True, max_length=225)),
                ('currency_symbol', models.CharField(max_length=225)),
                ('formal_name', models.CharField(max_length=225)),
            ],
        ),
    ]
