# Generated by Django 4.0.5 on 2022-08-01 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0002_gst_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tds_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tan_regno', models.IntegerField()),
                ('tan', models.IntegerField()),
                ('deductor_type', models.CharField(max_length=255)),
                ('deductor_branch', models.CharField(max_length=255)),
                ('person_details', models.CharField(max_length=255)),
                ('excemption_limit', models.CharField(max_length=255)),
                ('activate_tds', models.CharField(max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companies')),
            ],
        ),
    ]
