# Generated by Django 4.0.5 on 2022-08-01 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0004_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintain_accounts', models.CharField(max_length=255)),
                ('bill_wise_entry', models.CharField(max_length=255)),
                ('cost_centres', models.CharField(max_length=255)),
                ('interest_calc', models.CharField(max_length=255)),
                ('maintain_inventory', models.CharField(max_length=255)),
                ('integrate_accounts', models.CharField(max_length=255)),
                ('multiple_price_level', models.CharField(max_length=255)),
                ('batches', models.CharField(max_length=255)),
                ('expirydate_batches', models.CharField(max_length=255)),
                ('joborder_processing', models.CharField(max_length=255)),
                ('cost_tracking', models.CharField(max_length=255)),
                ('job_costing', models.CharField(max_length=255)),
                ('discount_invoices', models.CharField(max_length=255)),
                ('Billed_Quantity', models.CharField(max_length=255)),
                ('gst', models.CharField(max_length=255)),
                ('tds', models.CharField(max_length=255)),
                ('tcs', models.CharField(max_length=255)),
                ('vat', models.CharField(max_length=255)),
                ('excise', models.CharField(max_length=255)),
                ('servicetax', models.CharField(max_length=255)),
                ('payroll', models.CharField(max_length=255)),
                ('payroll_statutory', models.CharField(max_length=255)),
                ('multiple_addrss', models.CharField(max_length=255)),
                ('vouchers', models.CharField(max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companies')),
            ],
        ),
    ]
