# Generated by Django 4.0.5 on 2022-08-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0006_companies_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='fin_end',
            field=models.DateField(null=True),
        ),
    ]
