# Generated by Django 4.0.5 on 2022-08-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0009_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tds_details',
            name='tan',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tds_details',
            name='tan_regno',
            field=models.CharField(max_length=255),
        ),
    ]
